name: flutter_boilerplate_riverpod
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.4
  auto_route: 3.2.1
  intl: ^0.17.0
  meta: ^1.7.0
  dio: ^4.0.4
  json_annotation: ^4.4.0
  pretty_dio_logger: ^1.1.1
  flutter_secure_storage: 5.0.2
  google_fonts: ^2.2.0
  connectivity_plus: ^2.2.0
  shared_preferences: ^2.0.12
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  dartz: ^0.10.1
  get_it: ^7.2.0
  retrofit: ^3.0.1+1
  fluttericon: ^2.0.0
  responsive_framework: ^0.1.7
  date_format: ^2.0.6
  dropdown_button2: ^1.4.0
  datetime_picker_formfield: ^2.0.0

  firebase_auth: ^3.3.11
  firebase_core: ^1.14.0
  flutterfire_ui: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
  dart_code_metrics: ^4.8.1
  very_good_performance: ^0.0.4
  dependency_validator: ^3.1.2
  json_serializable:
  build_runner:
  flutter_gen_runner:
  retrofit_generator:
  freezed: 1.0.2
  auto_route_generator: 3.2.1
  import_sorter: ^4.6.0
  flutter_lints: ^1.0.0
  derry: ^1.4.3

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/core/gen/

assets:
  enabled: true
fonts:
  enabled: true
colors:
  enabled: true
  inputs:
    - assets/color/colors.xml
import_sorter:
  comments: true # Optional, defaults to true
  # ignored_files: # Optional, defaults to []
  # - \/lib\/*
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/
    - assets/

flutter_intl:
  enabled: true
  main_locale: vi
  class_name: S
  arb_dir: lib/core/l10n
  output_dir: lib/core/gen
